### ISSUE TITLE
Add no-array-index-key rule to eslint-config-triple

### ISSUE THREAD

**Issue by ChanelZM** [wearetriple/web-defaults#28]
The eslint rule react/no-array-index-key has been turned off manually in the eslint-config-triple package. My proposal would be to turn it on again as index as keys can cause rendering issues in some cases
![Screenshot 2024-01-08 at 11 10 27](https://github.com/wearetriple/web-defaults/assets/8983611/5ba0525b-3bd8-46a7-9779-0d676adda1e7)

**Comment by bfanger** [comment]
The following code:
```tsx
  const items = ["one", "two", "tree"];
  return (
    <ul>
      {items.map((item) => (
        <li>{item}</li>
      ))}
    </ul>
  );
```
Works as expected, but React complains about `Warning: Each child in a list should have a unique "key" prop.`

To satisfy React you'll need to write:

```tsx
  const items = ["one", "two", "three"];
  return (
    <ul>
      {items.map((item, i) => (
        <li key={i}>{item}</li>
      ))}
    </ul>
  );
```

Only string or number are allowed for keys:  `React.Key = string | number | bigint;`  (Svelte also allows using the object as key)

In a lot of cases there is no unique ID for the entries, enabling the `no-array-index-key` would lead to additional code and complexity without adding value.

**Comment by ChanelZM** [comment]
Understandable, but I think my view on it relates to the no-danger rule: enabling this opens a discussion for new developers. The new developer will either google why this warning is there or check with another developer. I agree this rule is not applicable to alle scenarios but having this rule totally turned off will not teach new developers when to use the rule thus implementing a bug, array items positioned in a different order, when the key is forgotten.

I think the benefit of having it on outweighs the benefit of turning it off. I rather use a disable comment sometimes that introducing bugs in the implementation when a code reviewer too misses the key in the implementation.

**Comment by ChanelZM** [comment]
Has been fixed
