### ISSUE TITLE
Add conventions for CSS

### ISSUE THREAD

**Issue by ChanelZM** [wearetriple/web-defaults#31]
I would like to suggest some conventions for CSS:

**Don't use an abbrevation in the classnames (as everyone can interpret it differently)**\
- Don't: `class="crsl"`
- Do: `class="carousel"`

**Avoid styling by id**
- Don't: `id="button"`
- Do: `class="button"`

**Use meaningful names**
- Don't: `class="section"`
- Do: `class="article-list"`

**Chain modifier classes**
- Don't: `class="button button-red"`
- Do: `class="button red"`

**Prefix state classes with 'is'**
 - Don't: `class="button button-disable"`
 - Do: `class="button is-disabled"`

**Keep it short but do sacrifice it for the sake of meaningful names**
- Don't: `class="most-read-blog-post-list-item"`
- Do: `class="most-read-post"`

**Avoid the use of !important**
- Don't: `color: var(--c-red) !important`
- Do: `color: var(--c-red)`

**Preferably style by classname**
- Don't: 
```
li {
  a {
    // properties
  }
}
```
- Do: 
```
.link {
  // properties
}
```

**Comment by RalphKocken** [comment]
Look great! How do you feel about nesting?

**Dont't:**
```
.navigation ul li a span {
 // properties
}
```

**Do:**
```
.navigation-link{
 // properties
}
```

**Comment by ChanelZM** [comment]
@RalphKocken not a fan of nesting! But that is already covered here: https://github.com/wearetriple/web-defaults/blob/main/naming.md
